version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: deploy site
          command: |
            . venv/bin/activate
            make s3_upload
